name: Bug Report
description: Report a problem you've encountered
title: '[Bug] '
labels: ['bug']
body:
  - type: textarea
    id: what
    attributes:
      label: What problem occurred?
      placeholder: e.g.) The timer finishes twice at 0 seconds
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please provide specific steps to reproduce the bug
      placeholder: |
        1. Go to the draw page
        2. Start the timer
        3. When it reaches 0 seconds...
    validations:
      required: false

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: e.g.) MacOS / Chrome 125
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Information
      placeholder: Please include screenshots or relevant logs if available
    validations:
      required: false
