name: 기능 제안
description: 새로운 기능 아이디어를 제안하고 싶을 때
title: "[기능 제안] "
labels: ["feature"]
body:
  - type: textarea
    id: what
    attributes:
      label: 제안하는 기능은 어떤 건가요?
      placeholder: 예) 타이머 시간을 사용자 지정할 수 있도록 설정 화면 추가
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: 왜 이 기능이 필요하다고 생각하시나요?
      placeholder: 예) 사용자가 원하는 시간만큼 집중할 수 있도록 유연성을 줍니다.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 참고 사항이나 관련 링크가 있다면 적어주세요
      placeholder: 디자인 예시, 레퍼런스 링크 등
    validations:
      required: false
