name: Feature Request
description: Suggest a new feature idea
title: '[Feature] '
labels: ['enhancement']
body:
  - type: textarea
    id: what
    attributes:
      label: What is the feature you are proposing?
      placeholder: e.g.) Add a settings screen to allow custom timer durations
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why do you think this feature is necessary?
      placeholder: e.g.) It provides flexibility for users to focus for their desired amount of time.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Please provide any references or related links.
      placeholder: Design examples, reference links, etc.
    validations:
      required: false
